tasks:
  - name: Setup and Install Dependencies
    init: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    command: |
      source venv/bin/activate
      python src/main.py

# (Optional) Specify IDE extensions
vscode:
  extensions:
    - ms-python.python
